import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { supabase } from "../lib/supabase";
import type { Establishment, Professional, Service } from "../types";
import { money, dateLongBR } from "../lib/utils";
import { CalendarDays, CheckCircle2, Clock3, MapPin, MessageCircle } from "lucide-react";

export function PublicBookingPage() {
  const {slug}=useParams();const [est,setEst]=useState<Establishment|null>(null);const [services,setServices]=useState<Service[]>([]);const [professionals,setProfessionals]=useState<Professional[]>([]);
  const [service,setService]=useState("");const [professional,setProfessional]=useState("");const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [slots,setSlots]=useState<string[]>([]);const [slot,setSlot]=useState("");const [name,setName]=useState("");const [phone,setPhone]=useState("");const [email,setEmail]=useState("");const [done,setDone]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{(async()=>{const {data:e}=await supabase.from("establishments").select("id,name,slug,description,phone,whatsapp,address,city,instagram,logo_url,cover_url,segment,plan").eq("slug",slug).maybeSingle();setEst(e);if(e){const [{data:s},{data:p}]=await Promise.all([supabase.from("services").select("*").eq("establishment_id",e.id).eq("active",true).order("name"),supabase.from("professionals").select("*").eq("establishment_id",e.id).eq("active",true).order("name")]);setServices(s||[]);setProfessionals(p||[]);}})()},[slug]);
  const selected=useMemo(()=>services.find(s=>s.id===service),[services,service]);
  useEffect(()=>{if(!est||!service||!professional||!date)return;supabase.rpc("get_available_slots",{p_establishment_id:est.id,p_service_id:service,p_professional_id:professional,p_date:date}).then(({data,error})=>{if(error){setSlots([]);return}setSlots((data||[]).map((x:any)=>x.slot))})},[est,service,professional,date]);
  async function book(){setError("");if(!est||!selected||!slot){setError("Escolha serviço, profissional, data e horário.");return}const {data,error}=await supabase.rpc("create_public_appointment",{p_establishment_id:est.id,p_service_id:selected.id,p_professional_id:professional,p_date:date,p_start_time:slot,p_customer_name:name,p_customer_phone:phone,p_customer_email:email||null});if(error){setError(error.message);return}if(data?.success===false){setError(data.message||"Esse horário não está mais disponível.");return}setDone(true)}
  if(!est)return <div className="grid min-h-screen place-items-center p-6 text-sm text-gray-500">{slug?"Carregando...":"Link inválido."}</div>;
  if(done)return <div className="grid min-h-screen place-items-center bg-gray-50 p-5"><div className="card w-full max-w-md p-8 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-green-50 text-green-600"><CheckCircle2 size={32}/></div><h1 className="mt-5 text-2xl font-black">Agendamento confirmado!</h1><p className="mt-2 text-sm text-gray-500">{dateLongBR(date)} às {slot.slice(0,5)}<br/>{selected?.name} com {professionals.find(p=>p.id===professional)?.name}</p>{est.whatsapp&&<a className="btn-primary mt-6 w-full" target="_blank" rel="noreferrer" href={`https://wa.me/${est.whatsapp.replace(/\D/g,"")}`}><MessageCircle size={17}/> Falar no WhatsApp</a>}</div></div>;
  return <div className="min-h-screen bg-gray-50"><div className="mx-auto max-w-xl p-4 sm:p-8">
    <div className="card overflow-hidden"><div className="bg-gray-900 p-7 text-white"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-xl bg-white text-gray-900"><CalendarDays/></div><div><h1 className="text-xl font-black">{est.name}</h1><p className="text-sm text-gray-400">{est.segment||"Negócio local"}{est.city?` • ${est.city}`:""}</p></div></div>{est.description&&<p className="mt-5 text-sm text-gray-300">{est.description}</p>}</div>
    <div className="p-5 sm:p-7"><div className="space-y-5">
      <div><label className="label">1. Escolha o serviço</label><div className="grid gap-2">{services.map(s=><button type="button" key={s.id} onClick={()=>setService(s.id)} className={`flex items-center justify-between rounded-xl border p-4 text-left ${service===s.id?"border-gray-900 bg-gray-50":"border-gray-200"}`}><span><b>{s.name}</b><span className="ml-2 text-xs text-gray-500">{s.duration_minutes} min</span></span><b>{money(s.price)}</b></button>)}</div></div>
      <div><label className="label">2. Escolha o profissional</label><select className="input" value={professional} onChange={e=>setProfessional(e.target.value)}><option value="">Selecione</option>{professionals.map(p=><option key={p.id} value={p.id}>{p.name}{p.specialty?` — ${p.specialty}`:""}</option>)}</select></div>
      <div><label className="label">3. Escolha a data</label><input className="input" type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></div>
      {service&&professional&&<div><label className="label">4. Horários disponíveis</label>{slots.length?<div className="grid grid-cols-3 gap-2 sm:grid-cols-4">{slots.map(s=><button type="button" key={s} onClick={()=>setSlot(s)} className={`rounded-xl border px-3 py-2.5 text-sm font-semibold ${slot===s?"border-gray-900 bg-gray-900 text-white":"border-gray-200 bg-white"}`}><Clock3 className="mr-1 inline" size={14}/>{s.slice(0,5)}</button>)}</div>:<div className="rounded-xl bg-gray-50 p-4 text-sm text-gray-500">Nenhum horário disponível para essa combinação.</div>}</div>}
      {slot&&<div className="border-t border-gray-100 pt-5"><label className="label">5. Seus dados</label><div className="grid gap-3"><input className="input" placeholder="Seu nome" value={name} onChange={e=>setName(e.target.value)} required/><input className="input" placeholder="WhatsApp" value={phone} onChange={e=>setPhone(e.target.value)} required/><input className="input" type="email" placeholder="E-mail (opcional)" value={email} onChange={e=>setEmail(e.target.value)}/></div><button type="button" className="btn-primary mt-4 w-full py-3" onClick={book}>Confirmar agendamento</button></div>}
      {error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    </div></div></div>
    <div className="mt-5 flex justify-center gap-4 text-xs text-gray-400">{est.address&&<span><MapPin className="mr-1 inline" size={13}/>{est.address}</span>}<span>AgendaPro Local</span></div>
  </div></div>;
}
